services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Admin@123
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    restart: unless-stopped

  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on: 
      - postgres
    restart: unless-stopped
  
  bsn-ui:
    container_name: bsn-ui
    image: bsn/bsn-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - bsn-api
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
