spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: root
    password: Admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: root
    password: Admin@123
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
         enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"

application:
  file:
    upload:
      photos-output-path: ./uploads

server:
  port: 8088

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html